"""Formatting utilities for the SpiritAI chat corpus.

This module enforces the standard prompt format required by the model
during both training and inference.
"""

from __future__ import annotations

# Special tokens used to delimit turns
USER_PROMPT_PREFIX = "USER_PROMPT"
AI_RESPONSE_PREFIX = "AI_RESPONSE"
END_OF_TURN = "END_OF_TURN"

def format_chat_turn(user_input: str, ai_response: str) -> str:
    """Format a single user/AI interaction into the standard corpus format.

    Args:
        user_input: The text provided by the user.
        ai_response: The text generated by the AI.

    Returns:
        The formatted interaction string ending with the turn delimiter.
    """
    return f"{USER_PROMPT_PREFIX} {user_input.strip()}\n{AI_RESPONSE_PREFIX} {ai_response.strip()}\n{END_OF_TURN}"

def format_prompt(user_input: str) -> str:
    """Format a user input string as a prompt for the model to complete.

    Args:
        user_input: The text provided by the user.

    Returns:
        The formatted prompt string ready for inference.
    """
    return f"{USER_PROMPT_PREFIX} {user_input.strip()}\n{AI_RESPONSE_PREFIX} "
